---
hosts: all
become: yes
tasks:
- name: install and update apache2
  yum:
    name: httpd
    state: present
- name: restart apache2
  service:
    name: httpd
    state: restarted
    enabled: yes
- name: install php and my sql
  yum:
   name: "{{ item }}"
   state: present
  with_items:
   -php
   -php-mysql
- name: restart apache2
  service:
    name: httpd
    state: restarted




